# Site settings
title: Hello HanYong
subtitle: "Journal of Han Yong Wunrow"
email: your-email@domain.com
description: "안녕 한용"
baseurl: ""
url: "hanyongwunrow.me"
twitter_username: "hyonerow"
github_username:  "hwunrow"
instagram_username: "hyonerow"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
