# Site Settings
title: Hello Han Yong
email: wunro007[at]umn[at]com
description: Obligatory disclosure: This site is not an official Fulbright Program site. The views expressed on this site are entirely mine and do not represent the views of the Fulbright Program, the U.S. Department of State, or any of its partner organizations.
baseurl: "/Fulbright" # the subpath of your site, e.g. /blog
url: "https://www.hanyongwunrow.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jekflix
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: hwunrow
twitter_username: @hyonerow
linkedin_username: hwunrow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
