# Site Settings
title: Hello Han Yong
email: wunro007[at]umn[at]com
description: Hello World
baseurl: "/Fulbright" # the subpath of your site, e.g. /blog
url: "www.hanyongwunrow.me" # the base hostname & protocol for your site
google_analytics: "UA-109139903-1"

# User Settings
username: Jekflix
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: hwunrow
twitter_username: @hyonerow
linkedin_username: hwunrow

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /Fulbright
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
